### ISSUE TITLE
Meer data

### ISSUE THREAD

**Issue by sweebee** [GidoHakvoort/rova#2]
is het mogelijk meer data op te halen ipv alleen de eerst volgende datum voor elke afval soort?

**Comment by GidoHakvoort** [comment]
Voorheen niet maar ik zag dat Rova hun website en afvalkalender heeft aangepast. Zag hier al wel meerdere dagen tussen staan - eens kijken of we daar wat mee kunnen.

**Comment by JeroenEeuwes** [comment]
Je krijgt (heel veel) meer gegevens met een andere api call. Ik heb de apikey uit de communicatie van de Rova app gehaald. Ik weet niet hoe lang die gedlig blijft. Als je in onderstaande url een geldige postocde, huisnummer en -toevoeging opgeeft krijg je heel veel terug. Bijvoorbeeld welke afval bij welke afvalsoort mag maar ook de ophaaldagen van het hele jaar.

http://api.inzamelkalender.rova.nl/webservices/appsinput/?postcode=1234XX&street=&huisnummer=1234&toevoeging=AB&apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&platform=phone&langs=nl&mobiletype=android&version=3&app_name=rova

Tenzij je dit heel graag wil weten is de api die nu wordt gebruikt wel veel sneller/minder gegevens.

**Comment by Devqon** [comment]
Ik ben ook op zoek naar wat meer data, omdat ik deze api gebruik in Home Assistant, waarbij er vaak 'Onbekend' wordt weergegeven. Het lijkt erop dat de api alleen de komende 14 dagen teruggeeft (hetzelfde als op de ROVA website).

> Voorheen niet maar ik zag dat Rova hun website en afvalkalender heeft aangepast. Zag hier al wel meerdere dagen tussen staan - eens kijken of we daar wat mee kun

Op de pagina waar dit getoond wordt komt dit helaas niet uit een api-call maar rechtstreeks met de html geserveerd. Het kan eventueel ge-scraped worden maar dan zal het niet in de officiele HA komen (web-scraping wordt actief buiten de core-components gehouden).

**Comment by JeroenEeuwes** [comment]
@Devqon Ik heb nog geen api call kunnen vinden die alleen de ophaaldagen doorgeeft voor een postcode, maar dan meer dan alleen de komende paar.

De api call die ik hierboven noemt geeft alle dagen van het huidige jaar door (en nog veel meer). Ik neem aan dat er in december ook de ophaaldagen van het komende jaar in komen te staan.

**Comment by sweebee** [comment]
@JeroenEeuwes bedankt! hier kan ik wat mee.

**Comment by GidoHakvoort** [comment]
Heb de library iets uitgebreid zodat ook de api vanuit Rova's mobile app als data source gebruikt kan worden (staat als default). Let op dat deze een heel jaar ophaalt bij elke update en per jaar kijkt (nu dus t/m 2020-12-31).
