### ISSUE TITLE
Not valid credentials :-(

### ISSUE THREAD

**Issue by acohin** [GidoHakvoort/rova#3]
Hoi!

Het lijkt er op dat Rova geen zin meer heeft om mee te werken aan publieke requests, of in ieder geval de api dusdanig heeft aangepast dat de afvalkalender niet meer met de huidige staat van de library opgehaald kan worden.

Ik heb een tijdje geleden geprobeerd om de afvalkalender [met HomeAssistant uit te lezen](https://www.home-assistant.io/integrations/rova/) maar dit leverde steeds de volgende fout op in de log:

```
ERROR (MainThread) [homeassistant.components.sensor] rova: Error on device update!
Traceback (most recent call last):
[...]
  File "/usr/src/homeassistant/homeassistant/components/rova/sensor.py", line 145, in update
    date = datetime.strptime(item["Date"], "%Y-%m-%dT%H:%M:%S")
TypeError: string indices must be integers
```
Na hier een tijdje niets mee gedaan te hebben toch maar even op onderzoek uit gegaan (negeer mijn legendarische python skills aub):

![image](https://user-images.githubusercontent.com/10961902/78673416-64f5e500-78e2-11ea-90b9-c629f940b988.png)

Merk op dat `is_rova_area()` nog wel gewoon netjes TRUE teruggeeft, maar dat `get_calendar_items()` het laat afweten. 

Ik heb het hele verhaal ook even nagelopen met een rest client waarbij ik hetzelfde terug zie.

**Comment by JeroenEeuwes** [comment]
Op de rova website werkt dit adres ook niet meer. Waarschijnlijk hebben ze de postcodes beter in het systeem staan. In het centrum hebben ze niet overal rolcontainers, maar vaak ondergrondse containers. Dus daar kan je ook niet vragen wanneer ze die komen legen.

Als je een andere postcode probeert van 1 van de buitenwijken (en dan niet een appartementencomplex waar ze ook ondergrondse containers hebben) werkt het wel.

**Comment by acohin** [comment]
Dat was even een voorbeeld, het klopt dat ze niet de standaard kliko service doen bij het gemeentehuis. ;-) 

Als ik kijk naar een willekeurig adres op de Robbeknolerf in Schothorst, met postcode 3813 LM nr 7, wat zeker weten een normaal woonhuis met rolcontainers is, dan zie je hetzelfde:

![image](https://user-images.githubusercontent.com/10961902/84577687-f1c78e00-adbe-11ea-8a39-89e3f0583c5b.png)

Zelfde als ik een willekeurig adres in Vathorst pak.

Het probleem is niet een verkeerd adres, maar dat de library niet meer tegen huidige versie van de afvalkalender api kan praten doordat de Rova mogelijk iets in de authenticatie heeft aangepast.

**Comment by JeroenEeuwes** [comment]
Als ik dat adres rechtstreeks probeer met curl werkt het anders prima:
`curl --cookie "RovaLc_inwoners={\"Id\":123123,\"ZipCode\":\"3813LM\",\"HouseNumber\":\"7\",\"HouseAddition\":\"\"}" https://www.rova.nl/api/TrashCalendar/GetCalendarItems?portal=inwoners`
geeft dit resultaat:
`[{"GarbageTypeCode":"PAPIER","GarbageType":"Papier","Date":"2020-06-19T00:00:00","Regular":true},{"GarbageTypeCode":"GFT","GarbageType":"GFT","Date":"2020-06-23T00:00:00","Regular":true},{"GarbageTypeCode":"PMD","GarbageType":"PMD","Date":"2020-06-30T00:00:00","Regular":true}]`

Ik weet eigenlijk niets van python af dus ik weet niet wat er mis gaat in de code. Maar voor zover ik het zie werkt de website prima. 

Ik dacht eerst dat het misschien aan de spatie in de postcode ligt maar dat werkt prima. Als de postcode niet klopt krijg je een andere melding, namelijk "Geen locatie". Misschien gaat er iets mis bij het aanmaken van het cookie?

**Comment by GidoHakvoort** [comment]
@acohin, @JeroenEeuwes thanks voor het uitzoeken en de input. Inmiddels is het vakantie dus heb'k wat meer tijd om eens te kijken of'k deze weer up-to-date kan krijgen. Ik houd jullie wel even op de hoogte!

**Comment by GidoHakvoort** [comment]
@acohin, @JeroenEeuwes Zover ik nu kan zien lijkt de API gewoon te werken. Probleem zoals hierboven beschreven komt door de opgegeven postcode. Deze moet zonder spatie, dus "3813LM" in plaats van "3813 LM". Ik zal dit issue sluiten maar ga nog wel even verder kijken waarom het binnen HA niet lijkt te werken en naar de mogelijkheid om nog meer data toe te voegen.

**Comment by yann1420** [comment]
Ik zie dat jullie deze API gebruiken om er binnen Home Assitant mee te werken. Heeft iemand beschreven hoe de API te integreren in HA ?
TiA, Jan

**Comment by GidoHakvoort** [comment]
Dag @yann1420, als het goed is staat dit beschreven op [https://www.home-assistant.io/integrations/rova/](https://www.home-assistant.io/integrations/rova/)?
